services:

  frontend:
    build:
        context: ./hyrde.challenge.ui
        dockerfile: Dockerfile
    image: theaaltje23/hyrde-holiday-weather-api-frontend
    ports: 
      -  "9000:9000"
    depends_on:
      - backend

  backend:
    build:
        context: ./Hyrde.Challenge
        dockerfile: Dockerfile
    image: theaaltje23/hyrde-holiday-weather-api-backend
    ports: 
       - "5114:5114"
    environment:
       - ASPNETCORE_URLS=http://*:5114
    depends_on:
        - db
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: weather_api
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Hyrde.Challenge/sql_dump:/docker-entrypoint-initdb.d

volumes:
  db_data: